name: '@primer/publish'
description: 'Publish Primer projects to npm with GitHub Design Systems conventions'
inputs:
  release-branch:
    description: 'Branch that releases should be cut from (usually your default branch)'
    required: false
    default: 'master'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.release-branch }}